"""empty message

Revision ID: 842c39c04d89
Revises: a42b66f37522
Create Date: 2019-05-17 18:33:32.645662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '842c39c04d89'
down_revision = 'a42b66f37522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('last_sign_in', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_sign_in')
    # ### end Alembic commands ###
